[package]
name = "advent2019-rust"
version = "0.1.0"
authors = ["Harald Kraemer <tetha42@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
permutohedron = "0.2.4"
defaultmap = "0.5.0"
itertools = "0.9.0"